Added metrics
sensu-plugins/sensu-plugins-gluster pull request #3
Opened 2018-04-16 12:05 UTC by yuri-zubov

## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

#### Known Compatibility Issues

2018-04-18 02:23 UTC, majormoses requested changes
Overall I think it looks good just some minor tweaks.

2018-04-18 02:23 UTC, majormoses commented on lib/sensu-plugins-gluster/common_gluster.rb
> +        output "#{config[:scheme]}#{new_path}", value unless value.nil? || value.empty?
I think we should return `false` so that people can potentially rescue on it.

2018-04-18 02:23 UTC, majormoses commented on lib/sensu-plugins-gluster/common_gluster.rb
> +  def array_to_naming_hash(array, key_name, only = nil)
I think `only` is a bit ambiguous and should be renamed to something like `filter_keys`.

2018-04-18 11:15 UTC, yuri-zubov commented
@majormoses - fixed

2018-04-19 05:28 UTC, majormoses approved these changes

2018-04-19 05:29 UTC, merged

2018-04-19 05:36 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-gluster/versions/2.0.0